
cov: FORCE

	g++ -std=c++0x  -L/global/u1/e/elegnani/gsl-2.8/lib/ -I/global/u1/e/elegnani/gsl-2.8/include -shared -o curved_sky_covariances_tools.so -fPIC curved_sky_covariances_tools.cpp -lgsl -lgslcblas -O3

FORCE:
